server:
  port: 3000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://119.23.69.223:3306/sofeware_center?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false
mybatis:
  type-aliases-package: com.kun.server.dao.model
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
